https: true
host: 'makeless.io:8080'
name: 'makeless-docs'

files:
  - .vuepress/dist
  - .htaccess
  - Dockerfile

use:
  makeless-shared:
    - ssl:ssl

service:
  build:
    context: '%live_dir%'
    dockerfile: Dockerfile
  ports:
    - 80:80
    - 443:443