https: true
host: 'deployment.makeless.io:8080'
name: 'makeless-docs'

files:
  - .vuepress/dist
  - Dockerfile
  - .htaccess

use:
  makeless-shared:
    - ssl:ssl

service:
  build:
    context: '%live_dir%'
    dockerfile: Dockerfile
  ports:
    - 80:80